from pysynfig.objects.tags.Angle import Angle
from pysynfig.objects.tags.Animated import Animated
from pysynfig.objects.tags.Color import Color
from pysynfig.objects.tags.Composite import Composite
from pysynfig.objects.tags.Keyframe import Keyframe
from pysynfig.objects.tags.Layer import Layer
from pysynfig.objects.tags.MainCanvas import MainCanvas
from pysynfig.objects.tags.Meta import Meta
from pysynfig.objects.tags.Offset import Offset
from pysynfig.objects.tags.Point import Point
from pysynfig.objects.tags.Scale import Scale
from pysynfig.objects.tags.SkewAngle import SkewAngle
from pysynfig.objects.tags.Vector import Vector
from pysynfig.objects.tags.Waypoint import Waypoint
